# Generated by Django 5.0.6 on 2024-09-10 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
