# Generated by Django 5.0.6 on 2024-09-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_date', models.DateField()),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_score', models.IntegerField()),
            ],
        ),
    ]
